create extension if not exists pgcrypto;

create table public.warehouses (id uuid primary key default gen_random_uuid(), name text not null, code text not null unique, address text not null default '', status text not null default 'active' check(status in ('active','inactive')), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.profiles (id uuid primary key references auth.users(id) on delete cascade, full_name text not null default '', role text not null default 'Warehouse Staff' check(role in ('Inventory Manager','Warehouse Staff')), warehouse_id uuid references public.warehouses(id) on delete set null, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.categories (id uuid primary key default gen_random_uuid(), name text not null unique, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.locations (id uuid primary key default gen_random_uuid(), warehouse_id uuid not null references public.warehouses(id), name text not null, short_code text not null, type text not null check(type in ('storage','production','receiving','dispatch')), status text not null default 'active' check(status in ('active','inactive')), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(warehouse_id,short_code));
create table public.products (id uuid primary key default gen_random_uuid(), name text not null, sku text not null unique, category_id uuid references public.categories(id) on delete set null, unit text not null, reorder_point numeric(14,3) not null default 0 check(reorder_point>=0), default_warehouse_id uuid references public.warehouses(id), default_location_id uuid references public.locations(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.stock_items (id uuid primary key default gen_random_uuid(), product_id uuid not null references public.products(id), warehouse_id uuid not null references public.warehouses(id), location_id uuid not null references public.locations(id), on_hand numeric(14,3) not null default 0 check(on_hand>=0), reserved numeric(14,3) not null default 0 check(reserved>=0 and reserved<=on_hand), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(product_id,warehouse_id,location_id));
create table public.receipts (id uuid primary key default gen_random_uuid(), receipt_number text not null unique, vendor text not null, warehouse_id uuid not null references public.warehouses(id), scheduled_date timestamptz not null, reference text not null default '', status text not null default 'draft' check(status in ('draft','waiting','ready','done','canceled')), created_by uuid references public.profiles(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.receipt_lines (id uuid primary key default gen_random_uuid(), receipt_id uuid not null references public.receipts(id) on delete cascade, product_id uuid not null references public.products(id), expected_quantity numeric(14,3) not null check(expected_quantity>0), received_quantity numeric(14,3) not null check(received_quantity>0), unit text not null, location_id uuid not null references public.locations(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.deliveries (id uuid primary key default gen_random_uuid(), delivery_number text not null unique, customer text not null, source_warehouse_id uuid not null references public.warehouses(id), source_location_id uuid not null references public.locations(id), scheduled_date timestamptz not null, reference text not null default '', status text not null default 'draft' check(status in ('draft','waiting','ready','done','canceled')), created_by uuid references public.profiles(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.delivery_lines (id uuid primary key default gen_random_uuid(), delivery_id uuid not null references public.deliveries(id) on delete cascade, product_id uuid not null references public.products(id), requested_quantity numeric(14,3) not null check(requested_quantity>0), picked_quantity numeric(14,3) not null default 0 check(picked_quantity>=0 and picked_quantity<=requested_quantity), packed_quantity numeric(14,3) not null default 0 check(packed_quantity>=0 and packed_quantity<=requested_quantity), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.internal_transfers (id uuid primary key default gen_random_uuid(), transfer_number text not null unique, source_warehouse_id uuid not null references public.warehouses(id), source_location_id uuid not null references public.locations(id), destination_warehouse_id uuid not null references public.warehouses(id), destination_location_id uuid not null references public.locations(id), scheduled_date timestamptz not null, status text not null default 'draft' check(status in ('draft','waiting','ready','done','canceled')), created_by uuid references public.profiles(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), check(source_location_id<>destination_location_id));
create table public.transfer_lines (id uuid primary key default gen_random_uuid(), transfer_id uuid not null references public.internal_transfers(id) on delete cascade, product_id uuid not null references public.products(id), quantity numeric(14,3) not null check(quantity>0), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.stock_adjustments (id uuid primary key default gen_random_uuid(), adjustment_number text not null unique, product_id uuid not null references public.products(id), warehouse_id uuid not null references public.warehouses(id), location_id uuid not null references public.locations(id), system_quantity numeric(14,3) not null check(system_quantity>=0), counted_quantity numeric(14,3) not null check(counted_quantity>=0), reason text not null, status text not null default 'draft' check(status in ('draft','applied')), created_by uuid references public.profiles(id), scheduled_date timestamptz not null default now(), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.move_history (id uuid primary key default gen_random_uuid(), occurred_at timestamptz not null default now(), reference text not null, operation text not null check(operation in ('Receipt','Delivery','Internal Transfer','Adjustment')), product_id uuid not null references public.products(id), sku text not null, source text not null, destination text not null, quantity numeric(14,3) not null, user_id uuid references public.profiles(id), status text not null, document_id uuid not null, source_warehouse_id uuid references public.warehouses(id), source_location_id uuid references public.locations(id), destination_warehouse_id uuid references public.warehouses(id), destination_location_id uuid references public.locations(id), zero_difference boolean not null default false, created_at timestamptz not null default now(), check(operation<>'Adjustment' or zero_difference=(quantity=0)));
create table public.reordering_rules (id uuid primary key default gen_random_uuid(), product_id uuid not null references public.products(id), warehouse_id uuid not null references public.warehouses(id), location_id uuid not null references public.locations(id), min_qty numeric(14,3) not null check(min_qty>=0), max_qty numeric(14,3) not null check(max_qty>=min_qty), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(product_id,warehouse_id,location_id));
create table public.notifications (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.profiles(id) on delete cascade, title text not null, message text not null, read boolean not null default false, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.operation_status_history (id uuid primary key default gen_random_uuid(), entity_type text not null check(entity_type in ('receipt','delivery','transfer','adjustment')), entity_id uuid not null, status text not null, recorded_at timestamptz not null default now(), actor_id uuid references public.profiles(id), created_at timestamptz not null default now());
create index move_history_occurred_at_idx on public.move_history(occurred_at desc);
create index stock_items_location_idx on public.stock_items(product_id,warehouse_id,location_id);
create index status_history_entity_idx on public.operation_status_history(entity_type,entity_id,recorded_at);

create or replace function public.create_profile_for_auth_user() returns trigger language plpgsql security definer set search_path='' as $$
begin
  insert into public.profiles(id,full_name) values(new.id,coalesce(new.raw_user_meta_data->>'full_name',''));
  return new;
end $$;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.create_profile_for_auth_user();

create or replace function public.touch_updated_at() returns trigger language plpgsql as $$
begin new.updated_at=now(); return new; end $$;
do $$ declare t text; begin
  foreach t in array array['warehouses','profiles','categories','locations','products','stock_items','receipts','receipt_lines','deliveries','delivery_lines','internal_transfers','transfer_lines','stock_adjustments','reordering_rules','notifications'] loop
    execute format('create trigger touch_updated_at before update on public.%I for each row execute function public.touch_updated_at()',t);
  end loop;
end $$;

do $$ declare t text; begin
  foreach t in array array['warehouses','categories','locations','products','stock_items','receipts','receipt_lines','deliveries','delivery_lines','internal_transfers','transfer_lines','stock_adjustments','move_history','reordering_rules','operation_status_history'] loop
    execute format('alter table public.%I enable row level security',t);
    execute format('create policy authenticated_read on public.%I for select to authenticated using(true)',t);
  end loop;
end $$;
alter table public.profiles enable row level security;
create policy profile_org_read on public.profiles for select to authenticated using(true);
alter table public.notifications enable row level security;
create policy notifications_self_read on public.notifications for select to authenticated using(user_id=auth.uid());

create or replace function public.current_profile_role() returns text language sql stable security definer set search_path='' as $$
  select role from public.profiles where id=auth.uid()
$$;
create policy manager_write_warehouses on public.warehouses for all to authenticated using(public.current_profile_role()='Inventory Manager') with check(public.current_profile_role()='Inventory Manager');
create policy manager_write_categories on public.categories for all to authenticated using(public.current_profile_role()='Inventory Manager') with check(public.current_profile_role()='Inventory Manager');
create policy manager_write_locations on public.locations for all to authenticated using(public.current_profile_role()='Inventory Manager') with check(public.current_profile_role()='Inventory Manager');
create policy manager_write_products on public.products for all to authenticated using(public.current_profile_role()='Inventory Manager') with check(public.current_profile_role()='Inventory Manager');
create policy manager_write_rules on public.reordering_rules for all to authenticated using(public.current_profile_role()='Inventory Manager') with check(public.current_profile_role()='Inventory Manager');
create policy manager_insert_receipts on public.receipts for insert to authenticated with check(public.current_profile_role()='Inventory Manager');
create policy manager_update_receipts on public.receipts for update to authenticated using(public.current_profile_role()='Inventory Manager' and status<>'done') with check(public.current_profile_role()='Inventory Manager' and status<>'done');
create policy manager_delete_receipts on public.receipts for delete to authenticated using(public.current_profile_role()='Inventory Manager' and status='draft');
create policy manager_insert_deliveries on public.deliveries for insert to authenticated with check(public.current_profile_role()='Inventory Manager');
create policy manager_update_deliveries on public.deliveries for update to authenticated using(public.current_profile_role()='Inventory Manager' and status<>'done') with check(public.current_profile_role()='Inventory Manager' and status<>'done');
create policy manager_delete_deliveries on public.deliveries for delete to authenticated using(public.current_profile_role()='Inventory Manager' and status='draft');
create policy staff_insert_transfers on public.internal_transfers for insert to authenticated with check(public.current_profile_role() in ('Inventory Manager','Warehouse Staff'));
create policy staff_update_transfers on public.internal_transfers for update to authenticated using(public.current_profile_role() in ('Inventory Manager','Warehouse Staff') and status<>'done') with check(public.current_profile_role() in ('Inventory Manager','Warehouse Staff') and status<>'done');
create policy staff_delete_transfers on public.internal_transfers for delete to authenticated using(public.current_profile_role() in ('Inventory Manager','Warehouse Staff') and status='draft');
create policy staff_insert_adjustments on public.stock_adjustments for insert to authenticated with check(public.current_profile_role() in ('Inventory Manager','Warehouse Staff'));
create policy staff_update_adjustments on public.stock_adjustments for update to authenticated using(public.current_profile_role() in ('Inventory Manager','Warehouse Staff') and status='draft') with check(public.current_profile_role() in ('Inventory Manager','Warehouse Staff') and status='draft');
create policy staff_delete_adjustments on public.stock_adjustments for delete to authenticated using(public.current_profile_role() in ('Inventory Manager','Warehouse Staff') and status='draft');
